### ISSUE TITLE
iOS issues when showing notifications content

### ISSUE THREAD

**Issue by Knocks83** [binwiederhier/ntfy#940]
:lady_beetle: **Describe the bug**
Sometimes on iOS there are issues showing the notification content: I always DO receive it, but sometimes it only shows "New message".
When I open the app and try refreshing the notifications, I still cannot see them (even though I set a cache file).

:computer: **Components impacted**

Self-hosted ntfy server (Docker), iOS

:bulb: **Screenshots and/or logs**

![image](https://github.com/binwiederhier/ntfy/assets/22529815/8d40ef3a-7a48-4a43-b78f-5cfef04928ae)
![image](https://github.com/binwiederhier/ntfy/assets/22529815/de27ed95-fe47-4f15-89cb-1ed7c9b51c98)

:crystal_ball: **Additional context**

I did set a cache file, but I didn't set the caching time (so it should be 12h). The notification screenshot is kinda old and I checked in-app only today (so more than 12h later).
I did set the "upstream-base-url" to ntfy, and I did set the "base-url". The service is behind a reverse proxy, but I don't think it's a problem, because sometimes the notifications do work.
The 6 notifications in the screenshot got sent by 3 different devices and 6 different users.

**Comment by Javiito32** [comment]
Hello, I am experiencing the same problem, I have been able to verify in my case, that it only happens with a different priority than the default one.

**Comment by kWAYTV** [comment]
lucky you, i dont even get them xd

**Comment by Knocks83** [comment]
@Javiito32 weird, I'll try setting the priority to normal on one of my servers to check it out

**Comment by binwiederhier** [comment]
@Knocks83 What you are experiencing are two different things.

The fact that you cannot see notifications in the UI is a long standing bug that was just fixed in the TestFlight version of the app. You may try out the beta version here:

> 📢 A new version of the ntfy iOS app is currently in TestFlight. This version (hopefully) fixes the issues with the UI not properly refreshing, as well as fixes for subscriptions "getting lost". It contains no other fixes. More to come. To test the app, please use this TestFlight link: https://testflight.apple.com/join/P1fFnAm9

The fact that you are seeing "New message" means that your iPhone cannot reach your selfhosted ntfy server. This dynamic is explained here: https://ntfy.sh/docs/config/#ios-instant-notifications

**Comment by kWAYTV** [comment]
> @Knocks83 What you are experiencing are two different things.
> 
> The fact that you cannot see notifications in the UI is a long standing bug that was just fixed in the TestFlight version of the app. You may try out the beta version here:
> 
> > 📢 A new version of the ntfy iOS app is currently in TestFlight. This version (hopefully) fixes the issues with the UI not properly refreshing, as well as fixes for subscriptions "getting lost". It contains no other fixes. More to come. To test the app, please use this TestFlight link: https://testflight.apple.com/join/P1fFnAm9
> 
> The fact that you are seeing "New message" means that your iPhone cannot reach your selfhosted ntfy server. This dynamic is explained here: https://ntfy.sh/docs/config/#ios-instant-notifications

at least i'm trying it with no luck

**Comment by Knocks83** [comment]
@binwiederhier 
> The fact that you are seeing "New message" means that your iPhone cannot reach your selfhosted ntfy server. This dynamic is explained here: https://ntfy.sh/docs/config/#ios-instant-notifications

I don't think that's the issue, I followed the Javiito32 suggestion and switched to default priority for one server, and now it works just fine. You have also to consider that my three servers send notifications to the same ntfy server (which is accessible on the Internet), and since I made that change I now can see the notifications from 1 of 3 servers. If connectivity was the issue, I shouldn't be able to see that one server's notifications.

Regarding the ios-instant-notifications guide, I followed it when I set the server up. SInce I only send/receive 6 notifications per day, I didn't set the api key.

I'll try installing the testflight version and checking whether it'll fix this issue too.

**Comment by Knocks83** [comment]
Update: no luck on my side, the new version doesn't fix this issue. For now I'll just edit all my notifications and stop adding the priority header.
Just for reference, following are the before and after of the cURL I make to send notifications:
```bash
curl -H "Authorization: Bearer $TOKEN" -H "X-Tags: white_check_mark,floppy_disk" -H "X-Priority: 2" -d "Backup to Hetzner completed succesfully at $(date '+%d/%m/%Y %H:%M:%S')" $URL &> /dev/null

curl -H "Authorization: Bearer $TOKEN" -H "X-Tags: white_check_mark,floppy_disk" -d "Backup to Hetzner completed succesfully at $(date '+%d/%m/%Y %H:%M:%S')" $URL &> /dev/null
```

**Comment by wunter8** [comment]
@Knocks83 I'm pretty sure the priority issue will be fixed by the next server release. I don't think it was supposed to be fixed just in the new TestFlight version

**Comment by kWAYTV** [comment]
Confirmed the beta app fixed the notifications issue for me now.
